name: Yaml for git to Deploy
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init
        working-directory: ${{ github.workspace }}


