name: Yaml for git to Deploy
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Terraform init
        run: terraform init
        working-directory: ${{ github.workspace }}
  job2:
    runs-on: self-hosted
    steps:
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.workspace }}


