name: Yaml for git to Deploy
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  job:
    runs-on: self-hosted
    steps:
      - name: Terraform init
        run: terraform init
        working-directory: /Users/rjv/actions-runner/_work/dev-rg-classic/dev-rg-classic


